language: java
sudo: false # faster builds

jdk:
  - oraclejdk8
script: 
  - ant -file com.java/build.xml
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test -B
  - "mvn cobertura:cobertura"
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
  
  
